nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@expo-*"
  - "@expo/*"
  - "@oxfmt/*"
  - "@oxlint/*"
  - "@oxlint-tsgolint/*"
  - "@tailwindcss/*"
  - babel-preset-expo
  - expo
  - expo-*
  - oxlint
  - oxlint-tsgolint
  - oxfmt
  - react-*
  - react
  - tailwindcss
