/* !!! This is code generated by a script. Do not edit directly. !!! */
/** biome-ignore-all assist/source/organizeImports: generated file */
/** biome-ignore-all lint: generated file */
/* eslint-disable */
// @ts-nocheck
/*
 * This is a barrel export file for all the icons in this directory as React components.
 *
 * 🟢 You can import this file directly.
 * Generated on: Wed Feb 11 09:38:14 PM WAT 2026
 */
export { default as IconArchive } from "./archive.svg?component";
export { default as IconArrowLeft } from "./arrow-left.svg?component";
export { default as IconCheckmark } from "./checkmark.svg?component";
export { default as IconChevronRight } from "./chevron-right.svg?component";
export { default as IconClock } from "./clock.svg?component";
export { default as IconCross } from "./cross.svg?component";
export { default as IconDelete } from "./delete.svg?component";
export { default as IconFontMonospace } from "./font-monospace.svg?component";
export { default as IconFontSansSerif } from "./font-sans-serif.svg?component";
export { default as IconFontSerif } from "./font-serif.svg?component";
export { default as IconFont } from "./font.svg?component";
export { default as IconGoogle } from "./google.svg?component";
export { default as IconHidePassword } from "./hide-password.svg?component";
export { default as IconHome } from "./home.svg?component";
export { default as IconInfo } from "./info.svg?component";
export { default as IconLock } from "./lock.svg?component";
export { default as IconLogo } from "./logo.svg?component";
export { default as IconLogout } from "./logout.svg?component";
export { default as IconMenu } from "./menu.svg?component";
export { default as IconMoon } from "./moon.svg?component";
export { default as IconPlus } from "./plus.svg?component";
export { default as IconRefresh } from "./refresh.svg?component";
export { default as IconSearch } from "./search.svg?component";
export { default as IconSettings } from "./settings.svg?component";
export { default as IconShowPassword } from "./show-password.svg?component";
export { default as IconStatus } from "./status.svg?component";
export { default as IconSun } from "./sun.svg?component";
export { default as IconSystemTheme } from "./system-theme.svg?component";
export { default as IconTag } from "./tag.svg?component";
